{% set name = "rubin-sim-all" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsst/rubin_sim/archive/refs/tags/{{ version }}.tar.gz
  sha256: 84b3ea350d244660b1c40addd0fb393e6efd8097354a05104551421c2f8b3fc7

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: rubin_sim
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('rubin-sim', exact=True) }}
    test:
      imports:
        - rubin_sim

  - name: rubin-sim
    version: {{ version }}
    script: run_sim_build.sh
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - matplotlib-base
        - healpy
        - pandas
        - palpy
        - scipy
        - sqlite
        - sqlalchemy
        - astropy
        - h5py
        - openorb
        - openorb-data-de405
        - astroplan
        - george
        - scikit-learn
        - six
        - numexpr
        - numba
        - pytables
        - colorcet
        - cycler
        - requests
        - shapely
        - skyfield
        - tqdm
    test:
      imports:
        - rubin_sim

about:
  home: https://github.com/lsst/rubin_sim
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Scheduler, survey strategy analysis, and other simulation tools for Rubin Observatory.

extra:
  recipe-maintainers:
    - tribeiro
    - rhiannonlynne
    - beckermr
