{% set name = "rubin-sim-all" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsst/rubin_sim/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7af7fcb1e54e7d22d2df25719e3b538aea005eff1572ca878618bb931ac30d71

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: rubin_sim
    version: {{ version }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('rubin-sim', exact=True) }}
    test:
      imports:
        - rubin_sim

  - name: rubin-sim
    version: {{ version }}
    script: run_sim_build.sh
    requirements:
      host:
        - python
        - pip
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - matplotlib-base
        - healpy
        - pandas
        - palpy
        - scipy
        - sqlite
        - sqlalchemy
        - astropy
        - h5py
        - openorb
        - openorb-data-de405
        - astroplan
        - george
        - scikit-learn
        - six
        - numexpr
        - numba
        - pytables
        - colorcet
        - cycler
        - requests
        - shapely
        - skyfield
        - tqdm
    test:
      imports:
        - rubin_sim

about:
  home: https://github.com/lsst/rubin_sim
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Scheduler, survey strategy analysis, and other simulation tools for Rubin Observatory.

extra:
  recipe-maintainers:
    - tribeiro
    - rhiannonlynne
    - beckermr
